export const data = {
  layout: [
    {
      i: "logo",
      x: 0,
      y: 0,
      w: 2,
      h: 6,
      static: false,
      maxW: 2,
      maxH: 8,
      minW: 1,
      minH: 1,
    },
    {
      i: "header",
      x: 4,
      y: 8,
      w: 12,
      h: 2,
      maxW: 12,
      maxH: 4,
      minW: 5,
      minH: 1,
    },
    {
      i: "title",
      x: 5,
      y: 0,
      w: 5,
      h: 1,
      maxW: 7,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "inv_no",
      x: 8,
      y: 12,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "inv_date",
      x: 8,
      y: 13,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "due_date",
      x: 8,
      y: 14,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "vat_tin_1",
      x: 5,
      y: 2,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 1,
      minW: 4,
      minH: 1,
    },
    {
      i: "address_1",
      x: 3,
      y: 3,
      w: 7,
      h: 2,
      maxW: 10,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "address_2",
      x: 0,
      y: 13,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_1",
      x: 2,
      y: 12,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "text_2",
      x: 2,
      y: 13,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "text_3",
      x: 2,
      y: 14,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 3,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_4",
      x: 10,
      y: 12,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_5",
      x: 10,
      y: 13,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_6",
      x: 10,
      y: 14,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_7",
      x: 2,
      y: 0,
      w: 3,
      h: 1,
      maxW: 3,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_8",
      x: 2,
      y: 2,
      w: 3,
      h: 1,
      maxW: 3,
      maxH: 1,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_9",
      x: 2,
      y: 3,
      w: 1,
      h: 2,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_10",
      x: 2,
      y: 5,
      w: 1,
      h: 2,
      maxW: 3,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "text_11",
      x: 0,
      y: 11,
      w: 12,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "text_12",
      x: 0,
      y: 15,
      w: 4,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "text_13",
      x: 0,
      y: 16,
      w: 4,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 4,
      minH: 1,
    },
    {
      i: "company_name_1",
      x: 0,
      y: 12,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "phone_1",
      x: 0,
      y: 14,
      w: 2,
      h: 1,
      maxW: 2,
      maxH: 2,
      minW: 1,
      minH: 1,
    },
    {
      i: "phone_2",
      x: 3,
      y: 5,
      w: 7,
      h: 2,
      maxW: 10,
      maxH: 2,
      minW: 5,
      minH: 1,
    },
    {
      i: "space_1",
      x: 0,
      y: 7,
      w: 12,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 12,
      minH: 1,
      static: false,
    },
    {
      i: "space_2",
      x: 0,

      y: 10,
      w: 12,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 12,
      minH: 1,
      static: false,
    },
  ],
  items: [
    {
      key: "logo",
      data: {
        type: "image",
        value:
          "https://inv-api.kosign.dev/api/files/26e87ce2-46a2-4084-a772-cf3003c91943.png",
        alt: "logo",
      },
    },
    {
      key: "header",
      data: {
        type: "text",
        value: `វិក័យបត្រអាករ
TAX INVOICE `,
        fontSize: "text-base",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-center",
        letterSpace: " leading-normal",
        backgroundColor: "",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "title",
      data: {
        type: "text",
        value: "CAMBODIAN SECURITY COPS CO.,LTD",
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "inv_no",
      data: {
        type: "text",
        value: `លេខរៀងវិក្កយបត្រ
INVOICE No,`,
        fontSize: "text-[10px]",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },

    {
      key: "inv_date",
      data: {
        type: "text",
        value: `កាលបរិច្ឆេត
Invoice Date`,
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        fontFamily: "font-mono font-siemreap",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "due_date",
      data: {
        type: "text",
        value: `ថ្ងៃផុតកំណត់បង់ប្រាក់
Due Date`,
        fontSize: "text-[10px]",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "vat_tin_1",
      data: {
        type: "vat_1",
        value: "L000-000000000",
        fontSize: "text-[10px]",
      },
    },
    {
      key: "address_1",
      data: {
        type: "text",
        value: `ផ្ទះលេខ 705 TK24ផ្លូវ 315សង្កាត់ បឹងកក់ទី 2 ខណ្ឌ ទួលគោក រាជធានីភ្នំពេញ
#705 TK25, St.315, Sangkat Boeng kok2, Khan Toulkok, Phnom Penh , Cambodia`,
        fontSize: "text-sm",
        fontFamily: "font-siemreap font-mono",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "address_2",
      data: {
        type: "text",
        value: `អាសយដ្ឋាន
Address `,
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        fontFamily: "font-mono font-siemreap",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_1",
      data: {
        type: "text",
        value: `K.O.S.I.G.N CAMBODIA Investment Co.,Ltd
ខេ.អូ.អេស.អាយ.ជី.អិន (ខេមបូឌា) អុិនវេសមេន`,
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        fontFamily: "font-mono font-siemreap",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_2",
      data: {
        type: "text",
        value:
          "Russian Federation Blvd. (#110, Sangkat Toeuk Thla, Khan Toulkok, Phnom Penh, Cambodia)",
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        fontFamily: "font-mono font-siemreap",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_3",
      data: {
        type: "text",
        value: "855 93 943 934",
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        fontFamily: "font-mono font-siemreap",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_4",
      data: {
        type: "text",
        value: "AB202403020001",
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_5",
      data: {
        type: "text",
        value: "14/03/2024",
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_6",
      data: {
        type: "text",
        value: "14/03/2024",
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        whiteSpace: "whitespace-pre",
        letterSpace: "  leading-normal",
      },
    },
    {
      key: "text_7",
      data: {
        type: "text",
        value: "ខេមបូឌាន សុីឃ្យូរីធី ខប",
        fontSize: "text-sm",
        fontFamily: "font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_8",
      label: "លេខអត្តសញ្ញាណកម្ម អតប (VAT TIN)",
      data: {
        type: "text",
        value: "លេខអត្តសញ្ញាណកម្ម អតប (VAT TIN)",
        fontSize: "text-sm",
        fontFamily: "font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_9",
      data: {
        type: "text",
        value: `អាសយដ្ឋាន
Address `,
        fontSize: "text-sm",
        fontFamily: "font-siemreap font-mono ",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_10",
      data: {
        type: "text",
        value: `ទូរស័ព្ទលេខ
Phone`,
        fontSize: "text-sm",
        fontFamily: "font-siemreap font-mono",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_11",
      data: {
        type: "text",
        value: "អតិថិជន/Customer",
        fontSize: "text-sm",
        fontFamily: "font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_12",
      data: {
        type: "text",
        value: `ថ្ងៃប្រើប្រាស់សេវា ចាប់ពីថ្ងៃទី ដល់ថ្ងៃទី`,
        fontSize: "text-xs",
        fontFamily: "font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "text_13",
      label: `Service Period`,
      data: {
        type: "text",
        value: `Jun 01,2024 to Jun 30,2024`,
        fontSize: "text-xs",
        fontFamily: "font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "company_name_1",
      data: {
        type: "text",
        value: `ឈ្មោះសហគ្រាស ឬអតិថិជន
Campany Name or Customer`,
        fontSize: "text-[10px]",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        fontFamily: "font-mono font-siemreap",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "phone_1",
      data: {
        type: "text",
        value: `ទូរស័ព្ទលេខ
Phone`,
        fontSize: "text-[10px]",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "phone_2",
      data: {
        type: "text",
        value: `855 23 969 097`,
        fontSize: "text-sm",
        fontFamily: "font-siemreap font-mono",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "space_1",
      data: {
        type: "space",
        value: "",
      },
    },
    {
      key: "space_2",
      data: {
        type: "space",
        value: "",
      },
    },
  ],
};

export const dataFooter = {
  layout: [
    {
      i: "khqr_code",
      x: 0,
      y: 0,
      w: 2,
      h: 7,
      maxW: 4,
      maxH: 10,
      minW: 1,
      minH: 1,
    },
    {
      i: "pay_method",
      x: 2,
      y: 0,
      w: 2,
      h: 2,
      maxW: 6,
      maxH: 3,
      minW: 1,
      minH: 1,
    },
    {
      i: "bank_name",
      x: 2,
      y: 3,
      w: 3,
      h: 2,
      maxW: 6,
      maxH: 3,
      minW: 1,
      minH: 1,
    },
    {
      i: "billing_acc",
      x: 2,
      y: 5,
      w: 3,
      h: 3,
      maxW: 6,
      maxH: 4,
      minW: 1,
      minH: 1,
    },
    {
      i: "sub_total",
      x: 5,
      y: 0,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "vat",
      x: 5,
      y: 1,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "grand_total",
      x: 5,
      y: 4,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "grand_total_kh",
      x: 5,
      y: 6,
      w: 5,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "note",
      x: 0,
      y: 10,
      w: 6,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "list_1",
      x: 0,
      y: 11,
      w: 6,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "list_2",
      x: 0,
      y: 12,
      w: 6,
      h: 1,
      maxW: 6,
      maxH: 2,
      minW: 3,
      minH: 1,
    },
    {
      i: "f_space_1",
      x: 0,
      y: 9,
      w: 12,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "f_space_2",
      x: 0,
      y: 12,
      w: 12,
      h: 4,
      maxW: 12,
      maxH: 5,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "sub_amt",
      x: 10,
      y: 0,
      w: 2,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "vat_amt",
      x: 10,
      y: 2,
      w: 2,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "grand_amt",
      x: 10,
      y: 4,
      w: 2,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "grand_riel_amt",
      x: 10,
      y: 6,
      w: 2,
      h: 1,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "cus_sign",
      x: 0,
      y: 12,
      w: 6,
      h: 2,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
    {
      i: "seller_sign",
      x: 6,
      y: 12,
      w: 6,
      h: 2,
      maxW: 12,
      maxH: 2,
      minW: 1,
      minH: 1,
      static: false,
    },
  ],
  items: [
    {
      key: "khqr_code",
      data: {
        type: "image",
        value:
          "https://inv-api.kosign.dev/api/files/a5249902-dcb7-432f-80bd-30d21015dabb.jpg",
        alt: "khqr_code",
      },
    },
    {
      key: "pay_method",
      data: {
        type: "text",
        value: `វិធីបង់ប្រាក់
Payment Method`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "bank_name",
      data: {
        type: "text",
        value: `Bank name
Phnom Penh Commercial Bank`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "billing_acc",
      data: {
        type: "text",
        value: `Billing Account no.
0-000-0000000-0
Cambodia Security Cop`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
      },
    },
    {
      key: "sub_total",
      data: {
        type: "money",
        value: `សរុប (ដុល្លារ)/ Sub Total (USD)`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "vat",
      data: {
        type: "money",
        value: `អាករលើតម្លៃបន្ថែម ១០% (ដុល្លារ)/ VAT10% (USD)`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "grand_total",
      data: {
        type: "money",
        value: `សរុបរួម ១០% (ដុល្លារ)/ Grand Total (USD)`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "grand_total_kh",
      data: {
        type: "money",
        value: `សរុបរួមរៀល(រៀល)/ Grand Total (KHR) អត្រាប្តូរប្រាក់ 1$=4,090៛`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "note",
      data: {
        type: "text",
        value: `សម្គាល់ / Note`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
      },
    },
    {
      key: "list_1",
      data: {
        type: "list",
        value: `Team Leader = $310/month (12hours)`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
      },
    },
    {
      key: "list_2",
      data: {
        type: "list",
        value: `Ordinary Guard (Male) = $290/month (12hours)`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
      },
    },
    {
      key: "f_space_1",
      data: {
        type: "space",
        value: ``,
      },
    },
    {
      key: "f_space_2",
      data: {
        type: "space",
        value: ``,
      },
    },
    {
      key: "sub_amt",
      data: {
        type: "money",
        value: `$4,794.72`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "vat_amt",
      data: {
        type: "money",
        value: `$479.56`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "grand_amt",
      data: {
        type: "money",
        value: `$5,274.28`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: "  leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "grand_riel_amt",
      data: {
        type: "money",
        value: `R21,677,291`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-left",
        letterSpace: " leading-normal",
        boxBorder: "border-b",
      },
    },
    {
      key: "cus_sign",
      data: {
        type: "money",
        value: `ហត្ថលេខា និង ឈ្មោះអាជីវករ
Customer's Signature & Name`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-center",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
        boxBorder: `border-t`,
      },
    },
    {
      key: "seller_sign",
      data: {
        type: "money",
        value: `ហត្ថលេខា និង ឈ្មោះអ្នកលក់
Seller's Signature & Name`,
        fontSize: "text-sm",
        fontFamily: "font-mono font-siemreap",
        fontWeight: "font-semibold",
        textAlign: "text-center",
        letterSpace: "  leading-normal",
        whiteSpace: "whitespace-pre",
        boxBorder: `border-t`,
      },
    },
  ],
};

export const newHeader = {
  layout: [
    {
      i: "head",
      x: 0,
      y: 0,
      w: 2,
      h: 2,
      static: false,
      maxW: 12,
      maxH: 12,
      minW: 1,
      minH: 1,
    },
  ],
  items: [
    {
      key: "head",
      data: {
        type: "text",
        value: "",
      },
    },
  ],
};
export const newFooter = {
  layout: [],
  items: [],
};

export const fontSizes = [
  "text-xs",
  "text-sm",
  "text-base",
  "text-lg",
  "text-xl",
  "text-2xl",
];
export const fontWeights = [
  "font-thin",
  "font-light",
  "font-normal",
  "font-medium",
  "font-semibold",
  "font-bold",
  "font-extrabold",
];
export const fontFamilies = [
  "font-sans",
  "font-serif",
  "font-mono",
  "font-siemreap",
];

export const textAligns = ["text-left", "text-center", "text-right"];

export const fontStyles = ["not-italic", "italic"];

export const textDecorations = [
  "no-underline",
  "underline",
  "overline",
  "line-through",
];

export const boxBorders = [
  "none",
  "border",
  "border-l",
  "border-r",
  "border-t",
  "border-b",
];

export const DataBodyItems: BodyItemsState = {
  layout: [
    { i: "table", x: 0, y: 0, w: 12, h: 10, static: false, minH: 4, minW: 10 },
  ],
  items: [
    {
      key: "table", // key: "{{logo}}" , {"logo": "[alt: "ll"]"}
      data: {
        type: "table",
        content: [
          {
            thead: ["No", "Description", "Quantity", "Unit Price", "Amount"],
            props: {
              border: "border-1",
              fontFamily: "font-poppins",
              fontSize: "text-sm",
              fontWeight: "font-bold",
              textTransform: "none",
              backgroundColor: "#f4f4f4",
              color: "#000",
              textAlign: "text-center",
              padding: "p-2",
              whiteSpace: "whitespace-pre",
              lineHeight: "leading-normal",
            },
          },
          {
            tbody: [
              {
                no: 1,
                description: `A Shift`,
                unit_price: `$330.00`,
                quantity: `1`,
                amount: `$330.00`,
                subRow: [
                  {
                    description: `- Ordinary Guard (Male)`,
                    unit_price: `$330.00`,
                    quantity: `1`,
                    amount: `$330.00`,
                    subRow1: [],
                  },
                  {
                    description: `- Ordinary Guard (Female)`,
                    unit_price: `$430.00`,
                    quantity: `2`,
                    amount: `$860.00`,
                    subRow1: [
                      {
                        description: `- Sub Row 1`,
                        unit_price: `$330.00`,
                        quantity: `1`,
                        amount: `$330.00`,
                      },
                      {
                        description: `- Sub Row 2`,
                        unit_price: `$330.00`,
                        quantity: `1`,
                        amount: `$330.00`,
                      },
                    ],
                  },
                ],
              },
              // {
              //   no: 2,
              //   description: `C Shift`,
              //   unit_price: `$330.00`,
              //   quantity: `1`,
              //   amount: `$330.00`,
              //   subRow: [
              //     {
              //       description: `- Ordinary Guard (Male)`,
              //       unit_price: `$330.00`,
              //       quantity: `1`,
              //       amount: `$330.00`,
              //       subRow1: [
              //         {
              //           description: `- Sub Row 1`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //         {
              //           description: `- Sub Row 2`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //       ]
              //     },
              //     {
              //       description: `- Ordinary Guard (Female)`,
              //       unit_price: `$330.00`,
              //       quantity: `1`,
              //       amount: `$330.00`,
              //       subRow1: [
              //         {
              //           description: `- Sub Row 1`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //         {
              //           description: `- Sub Row 2`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //       ]
              //     },
              //   ],
              // },
              // {
              //   no: 3,
              //   description: `Service Overtime (Male)(2hours, 2.5hours and Other)`,
              //   unit_price: ``,
              //   quantity: ``,
              //   amount: ``,
              //   subRow: [
              //     {
              //       description: `- On Jun 2024 = 66h x $0.89= 58.74`,
              //       unit_price: `$330.00`,
              //       quantity: `1`,
              //       amount: `$330.00`,
              //       subRow1: [
              //         {
              //           description: `- Sub Row 1`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //         {
              //           description: `- Sub Row 2`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //       ]
              //     },
              //     {
              //       description: `- On may 2024 = 32h x $0.89= 28.48`,
              //       unit_price: `$330.00`,
              //       quantity: `1`,
              //       amount: `$330.00`,
              //       subRow1: [
              //         {
              //           description: `- Sub Row 1`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //         {
              //           description: `- Sub Row 2`,
              //           unit_price: `$330.00`,
              //           quantity: `1`,
              //           amount: `$330.00`,
              //         },
              //       ]
              //     },
              //   ],
              // },
            ],
            props: {
              border: "border-b",
              fontFamily: "font-mono",
              fontSize: "text-sm",
              fontWeight: "", //font-bold
              textTransform: "uppercase",
              backgroundColor: "#fff",
              color: "#000",
              textAlign: "",
              padding: "p-1",
              whiteSpace: "whitespace-pre",
              lineHeight: "leading-normal",
            },
          },
        ],
      },
    },
  ],
};

// export const newDataBodyItems: BodyItemsState ={layout: [
//   { i: "table", x: 0, y: 0, w: 12, h: 10, static: false, minH: 4, minW: 10 },
// ],
// items: [
//   {
//     key: "table", // key: "{{logo}}" , {"logo": "[alt: "ll"]"}
//     data: {
//       type: "table",
//       content: [
//         {
//           thead: ["No", "Description", "Quantity", "Unit Price", "Amount"],
//           props: {
//             border: "border-1",
//             fontFamily: "font-poppins",
//             fontSize: "text-sm",
//             fontWeight: "font-bold",
//             textTransform: "none",
//             backgroundColor: "#f4f4f4",
//             color: "#000",
//             textAlign: "text-center",
//             padding: "p-2",
//             whiteSpace: "whitespace-pre",
//             lineHeight: "leading-normal",
//           },
//         },
//         {
//           tbody: [],
//           props: {
//             border: "border-b",
//             fontFamily: "font-mono",
//             fontSize: "text-sm",
//             fontWeight: "", //font-bold
//             textTransform: "uppercase",
//             backgroundColor: "#fff",
//             color: "#000",
//             textAlign: "",
//             padding: "p-1",
//             whiteSpace: "whitespace-pre",
//             lineHeight: "leading-normal",
//           },
//         },
//       ],
//     },
//   },
// ],
// }

export const newDataBodyItems: BodyItemsState = { layout: [], items: [] };
